### ISSUE TITLE
Как добавить мультиязычность?

### ISSUE THREAD

**Issue by Fayozjon** [studio451/yiistudio#2]
Здравствуйте как сделать языки? и товары чтобы были мультиязычными
Хорошо поработали над easyiiCMS молодцы

**Comment by studio451** [comment]
День добрый! Пока мультиязычность в самой CMS не прорабатывалась - планируем. Есть только то, что предоставляет сам Yii2.
Да, в основе отличная работа от noumo [easyiiCMS](https://github.com/noumo/easyii).

**Comment by studio451** [comment]
Немного проработали мультиязычность:
https://github.com/studio451/yiistudio/tree/master/admin/messages

**Comment by Fayozjon** [comment]
Отлично, благодарю
