### ISSUE TITLE
sos

### ISSUE THREAD

**Issue by knopka2** [studio451/yiistudio#4]
вопрос, вы сами пробовали проделать установку ?

**Comment by studio451** [comment]
Да, конечно. Что не получается?

**Comment by hellyeah0** [comment]
ну, например, > php init --env=Development --overwrite=n
Could not open input file: init
Script php init --env=Development --overwrite=n handling the post-install-cmd event returned with error code 1

**Comment by studio451** [comment]
Команда php init --env=Development --overwrite=n - это запуск Yii Application Initialization Tool, скрипта который помогает настроить окружение для advanced шаблона приложения yii. Если вы хотите использовать YiiStudio, то здесь предлагается своя структура приложения, которая настроена сразу из коробки. Ее не нужно как-то инициализировать. В файле wwwroot/index.php используем стандартные константы YII_DEBUG, YII_ENV для настройки режимов работы.

**Comment by hellyeah0** [comment]
зачем вы мне это рассказываете?
у вас в composer.json
"scripts": {
        "post-install-cmd": "php init --env=Development --overwrite=n"
}

**Comment by studio451** [comment]
hellyeah0, спасибо, замечание принято.
